### ISSUE TITLE
Setup .xml failed while executing ANT build in ams

### ISSUE THREAD

**Issue by iqsougata** [iquesters/core#8]
Core version - 1.1.0.0

copy.version.properties:
     [echo] Copying version.properties to org/iq/version package

BUILD FAILED
F:\iquesters\git\ams\setup\setup.xml:22: The following error occurred while executing this line:
F:\iquesters\git\ams\setup\setup.xml:47: copy doesn't support the nested "present" element.

Total time: 925 milliseconds

**Comment by iqsam** [comment]
It seems you have changed the setup.xml.
You should NEVER change setup.xml yourself.
